project:
  type: website
  output-dir: docs

website:
  title: "Mitchell Horn"
 
  navbar:
    left:
      - text: "Publications"
        href: publications
      - text: "Talks"
        href: talks
      - text: "Tutorials"
        href: https://profiles.bu.edu/Mitchell.Horn
    right:
      - text: "BU Profile"
        href: https://profiles.bu.edu/Mitchell.Horn
      - icon: linkedin
        href: https://www.linkedin.com/in/mitchell-horn-92a279106/
      - icon: github
        href: https://github.com/mitchellxh
      - icon: twitter
        href: https://twitter.com/MitchellHorn_

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



